
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  aliyun:
    oss:
      endpoint: https://oss-cn-hangzhou.aliyuncs.com
      bucket-name: web-learn-zjx

  redis:
    host: 127.0.0.1
    port: 6666
    password: 123456

  wechat:
    secret: e6ad8333abad561532a7a8be471bd4b4
    appid: wx195a83ae94c0b947